

const FETCH_ORDER_CART_CONTENTS_SUCCESS = "FETCH_ORDER_CART_CONTENTS_SUCCESS"
const FETCH_ORDER_CART_CONTENTS_ERROR = "FETCH_ORDER_CART_CONTENTS_ERROR"
const FETCH_ORDER_CART_CONTENTS_REQUEST = "FETCH_ORDER_CART_CONTENTS_REQUEST"
const FETCH_ORDER_CART_CONTENTS_RESET = "FETCH_ORDER_CART_CONTENTS_RESET"




const actionsList = {
  FETCH_ORDER_CART_CONTENTS_SUCCESS,
  FETCH_ORDER_CART_CONTENTS_ERROR,
  FETCH_ORDER_CART_CONTENTS_REQUEST,
  FETCH_ORDER_CART_CONTENTS_RESET,
}

export type OrderCartActionList = keyof typeof actionsList

export type OrderCartActionType = {
  payload?: any,
  type: OrderCartActionList
}

export default {
  ...actionsList

}
